require "./liquid/assign_test"
require "./liquid/block_test"
require "./liquid/condition_test"
require "./liquid/context_test"
require "./liquid/drop_test"
require "./liquid/error_handling_test"
require "./liquid/file_system_test"
require "./liquid/filter_test"
require "./liquid/output_test"
require "./liquid/parsing_quirks_test"
require "./liquid/regexp_test"
require "./liquid/security_test"
require "./liquid/standard_filter_test"
require "./liquid/strainer_test"
require "./liquid/template_test"
require "./liquid/variable_test"

require "./liquid/tags/*"
